# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Հաշվողական գիտությունը դպրոցից
tagline:             'Computer Science for High School'
description:         'Մեր նպատական է ներդնել հաշվողական մեթոդները դպրոցում դասավանդվող դասապլանների մեջ։'
url:                 http://cs4hs-am.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hayk Saribekyan
  email:             cs4hs.am@gmail.com

# Custom vars
gems:               [jekyll-paginate,jekyll-gist]
